name: Build Arch ISO

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Maximize Build Space
        run: |
          # تنظيف الملفات الضخمة لتوفير مساحة كافية لبناء الـ ISO
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /usr/lib/jvm /usr/local/share/boost
          sudo apt-get clean
          df -h

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build ISO
        run: |
          mkdir -p out
          chmod 777 out

          docker run --rm --privileged \
            -v ${{ github.workspace }}:/repo \
            archlinux:latest \
            /bin/bash -c "
              # 1. تحديث النظام وتثبيت أدوات بناء الأيزو
              pacman -Sy --noconfirm archlinux-keyring && \
              pacman -Syu --noconfirm archiso git && \
              
              # 2. ضبط مستودع حلوان لقبول الحزم غير الموقعة (مؤقتاً للنجاح)
              sed -i 's/SigLevel    = Required DatabaseOptional/SigLevel = Optional TrustAll/g' /repo/pacman.conf && \

              # 3. معالجة قائمة الحزم (حذف التعارضات)
              sed -i '/^cheese$/d' /repo/packages.x86_64 && \

              # 4. الحل الفني لمشكلة الذاكرة (XZ RAM Fix)
              # تحديد نواتين وسقف ذاكرة 3 جيجا لضمان عدم انهيار الضغط
              # مع الحفاظ على مستوى ضغط مرتفع (-6) لتصغير الحجم
              export XZ_OPT='-T 2 -M 3G -6' && \

              # 5. بدء بناء الأيزو مع تخطي الأسئلة التفاعلية
              echo -e '\n' | yes | mkarchiso -v -w /tmp/archiso-work -o /repo/out /repo
            "

      - name: Upload ISO
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: Helwan-LTS-Cinnamon-ISO
          path: out/*.iso
